version: '3.8'
services:
  db:
    image: postgres:12.11
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
      TZ: Asia/Tokyo
    ports:
      - 5432:5432
    volumes:
      - ./db:/docker-entrypoint-initdb.d
  back:
    container_name: back
    build: ./back
    depends_on:
      - db
    ports:
      - 8080:8080
    tty: true
    volumes:
      - ./back/app:/app:cached
    working_dir: /app
  front:
    container_name: front
    build: ./front
    ports:
      - 4200:4200
    volumes:
      - ./front/app:/app:cached
    stdin_open: true
    tty: true
