spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test # DB名
    username: test # PostgreSQLのユーザ名
    password: test # PostgreSQLのパスワード
  security:
    user:
      name: user
      password: a
  
server:
  port: 8080
  servlet:
    context-path: /api
  
mybatis:
  type-aliases-package: jp.com.app.entity
  configuration: 
    mapUnderscoreToCamelCase: true
