spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://db:5432/test
    username: test
    password: test
  
server:
  port: 8081
  servlet:
    context-path: /api
  
mybatis:
  type-aliases-package: jp.com.app.entity
  configuration: 
    mapUnderscoreToCamelCase: true